export const cvFiles = [
  {
    id: 1,
    resourceId: 1,
    fileName: 'cv_nguyen_van_anh_2024.pdf',
    filePath: '/uploads/cv/cv_nguyen_van_anh_2024.pdf',
    fileType: 'pdf',
    fileSize: 1024000,
    originalName: 'CV_NguyenVanAnh_Updated.pdf',
    uploadedBy: 2,
    isActive: true,
  },
  {
    id: 2,
    resourceId: 2,
    fileName: 'cv_tran_thi_binh_2024.docx',
    filePath: '/uploads/cv/cv_tran_thi_binh_2024.docx',
    fileType: 'docx',
    fileSize: 856000,
    originalName: 'CV_TranThiBinh_Latest.docx',
    uploadedBy: 3,
    isActive: true,
  },
  {
    id: 3,
    resourceId: 3,
    fileName: 'cv_le_van_cuong_2024.pdf',
    filePath: '/uploads/cv/cv_le_van_cuong_2024.pdf',
    fileType: 'pdf',
    fileSize: 1200000,
    originalName: 'CV_LeVanCuong_DevOps.pdf',
    uploadedBy: 2,
    isActive: true,
  },
  {
    id: 4,
    resourceId: 4,
    fileName: 'cv_pham_thi_duyen_2024.pdf',
    filePath: '/uploads/cv/cv_pham_thi_duyen_2024.pdf',
    fileType: 'pdf',
    fileSize: 945000,
    originalName: 'CV_PhamThiDuyen_QA.pdf',
    uploadedBy: 5,
    isActive: true,
  },
  {
    id: 5,
    resourceId: 5,
    fileName: 'cv_hoang_van_enh_2024.docx',
    filePath: '/uploads/cv/cv_hoang_van_enh_2024.docx',
    fileType: 'docx',
    fileSize: 743000,
    originalName: 'CV_HoangVanEnh_Frontend.docx',
    uploadedBy: 3,
    isActive: true,
  },
  {
    id: 6,
    resourceId: 6,
    fileName: 'cv_vo_thi_fy_2024.pdf',
    filePath: '/uploads/cv/cv_vo_thi_fy_2024.pdf',
    fileType: 'pdf',
    fileSize: 1100000,
    originalName: 'CV_VoThiFy_BA.pdf',
    uploadedBy: 2,
    isActive: true,
  },
  {
    id: 7,
    resourceId: 7,
    fileName: 'cv_nguyen_van_giang_2024.pdf',
    filePath: '/uploads/cv/cv_nguyen_van_giang_2024.pdf',
    fileType: 'pdf',
    fileSize: 1300000,
    originalName: 'CV_NguyenVanGiang_Backend.pdf',
    uploadedBy: 4,
    isActive: true,
  },
  {
    id: 8,
    resourceId: 8,
    fileName: 'cv_tran_van_huy_2024.docx',
    filePath: '/uploads/cv/cv_tran_van_huy_2024.docx',
    fileType: 'docx',
    fileSize: 675000,
    originalName: 'CV_TranVanHuy_Tester.docx',
    uploadedBy: 5,
    isActive: true,
  },
  {
    id: 9,
    resourceId: 9,
    fileName: 'cv_le_thi_yen_2024.pdf',
    filePath: '/uploads/cv/cv_le_thi_yen_2024.pdf',
    fileType: 'pdf',
    fileSize: 987000,
    originalName: 'CV_LeThiYen_PM.pdf',
    uploadedBy: 2,
    isActive: true,
  },
  {
    id: 10,
    resourceId: 10,
    fileName: 'cv_pham_van_khanh_2024.pdf',
    filePath: '/uploads/cv/cv_pham_van_khanh_2024.pdf',
    fileType: 'pdf',
    fileSize: 1150000,
    originalName: 'CV_PhamVanKhanh_Mobile.pdf',
    uploadedBy: 3,
    isActive: true,
  },
];
