import { ActionType } from '../../common/types';

export const historyLogs = [
  {
    id: 1,
    resourceId: 1,
    actionType: ActionType.CREATE,
    oldValues: undefined,
    newValues: JSON.stringify({
      employeeCode: 'FJP001',
      fullName: 'Nguyen Van Anh',
      status: 'idle',
    }),
    description: 'Created new idle resource record',
    changedBy: 2,
    entityType: 'resource',
    entityId: 1,
  },
  {
    id: 2,
    resourceId: 2,
    actionType: ActionType.CREATE,
    oldValues: undefined,
    newValues: JSON.stringify({
      employeeCode: 'FJP002',
      fullName: 'Tran Thi Binh',
      status: 'idle',
    }),
    description: 'Created new idle resource record',
    changedBy: 2,
    entityType: 'resource',
    entityId: 2,
  },
  {
    id: 3,
    resourceId: 3,
    actionType: ActionType.UPDATE,
    oldValues: JSON.stringify({ status: 'idle' }),
    newValues: JSON.stringify({ status: 'processing' }),
    description: 'Updated resource status to processing',
    changedBy: 4,
    entityType: 'resource',
    entityId: 3,
  },
  {
    id: 4,
    resourceId: 1,
    actionType: ActionType.UPLOAD_CV,
    oldValues: undefined,
    newValues: JSON.stringify({
      fileName: 'cv_nguyen_van_anh_2024.pdf',
      fileSize: 1024000,
    }),
    description: 'Uploaded CV file',
    changedBy: 2,
    entityType: 'cv_file',
    entityId: 1,
  },
  {
    id: 5,
    resourceId: 4,
    actionType: ActionType.UPDATE,
    oldValues: JSON.stringify({ processNote: 'Available for assignment' }),
    newValues: JSON.stringify({ processNote: 'Urgent - Idle for over 2 months' }),
    description: 'Updated process note - marked as urgent',
    changedBy: 5,
    entityType: 'resource',
    entityId: 4,
  },
  {
    id: 6,
    resourceId: 8,
    actionType: ActionType.UPDATE,
    oldValues: JSON.stringify({ status: 'idle' }),
    newValues: JSON.stringify({ status: 'assigned' }),
    description: 'Resource assigned to new project',
    changedBy: 5,
    entityType: 'resource',
    entityId: 8,
  },
  {
    id: 7,
    resourceId: 7,
    actionType: ActionType.UPDATE,
    oldValues: JSON.stringify({ processNote: 'Looking for opportunities' }),
    newValues: JSON.stringify({ processNote: 'URGENT - Idle for over 3 months, need immediate action' }),
    description: 'Updated to urgent status - extended idle period',
    changedBy: 4,
    entityType: 'resource',
    entityId: 7,
  },
  {
    id: 8,
    resourceId: 9,
    actionType: ActionType.UPDATE,
    oldValues: JSON.stringify({ status: 'idle' }),
    newValues: JSON.stringify({ status: 'processing' }),
    description: 'Manager evaluating project opportunities',
    changedBy: 2,
    entityType: 'resource',
    entityId: 9,
  },
  {
    id: 9,
    resourceId: 6,
    actionType: ActionType.UPLOAD_CV,
    oldValues: undefined,
    newValues: JSON.stringify({
      fileName: 'cv_vo_thi_fy_2024.pdf',
      fileSize: 1100000,
    }),
    description: 'Uploaded updated CV file',
    changedBy: 2,
    entityType: 'cv_file',
    entityId: 6,
  },
  {
    id: 10,
    resourceId: 10,
    actionType: ActionType.CREATE,
    oldValues: undefined,
    newValues: JSON.stringify({
      employeeCode: 'FJP010',
      fullName: 'Pham Van Khanh',
      status: 'idle',
    }),
    description: 'Added new mobile developer to idle resources',
    changedBy: 3,
    entityType: 'resource',
    entityId: 10,
  },
];
