import { ResourceStatus } from '../../common/types';

export const idleResources = [
  {
    id: 1,
    employeeCode: 'FJP001',
    fullName: 'Nguyen Van Anh',
    departmentId: 1,
    position: 'Senior Developer',
    email: 'nv.anh@company.com',
    skillSet: 'React, Node.js, TypeScript, MongoDB',
    idleFrom: new Date('2024-07-01'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Waiting for new project assignment',
    rate: 2500.00,
    createdBy: 2,
    updatedBy: 2,
  },
  {
    id: 2,
    employeeCode: 'FJP002',
    fullName: 'Tran Thi Binh',
    departmentId: 1,
    position: 'Full-stack Developer',
    email: 'tt.binh@company.com',
    skillSet: 'Vue.js, Python, Django, PostgreSQL',
    idleFrom: new Date('2024-06-15'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Previous project completed, looking for new opportunities',
    rate: 2200.00,
    createdBy: 2,
    updatedBy: 3,
  },
  {
    id: 3,
    employeeCode: 'FJP003',
    fullName: 'Le Van Cuong',
    departmentId: 2,
    position: 'DevOps Engineer',
    email: 'lv.cuong@company.com',
    skillSet: 'Docker, Kubernetes, AWS, Jenkins, Terraform',
    idleFrom: new Date('2024-08-01'),
    idleTo: undefined,
    status: ResourceStatus.PROCESSING,
    processNote: 'In discussion with potential client',
    rate: 2800.00,
    createdBy: 2,
    updatedBy: 4,
  },
  {
    id: 4,
    employeeCode: 'FJP004',
    fullName: 'Pham Thi Duyen',
    departmentId: 3,
    position: 'QA Automation',
    email: 'pt.duyen@company.com',
    skillSet: 'Selenium, TestNG, Cypress, API Testing',
    idleFrom: new Date('2024-05-20'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Urgent - Idle for over 2 months',
    rate: 2000.00,
    createdBy: 2,
    updatedBy: 5,
  },
  {
    id: 5,
    employeeCode: 'FJP005',
    fullName: 'Hoang Van Enh',
    departmentId: 1,
    position: 'Frontend Developer',
    email: 'hv.enh@company.com',
    skillSet: 'React, Angular, JavaScript, CSS, HTML',
    idleFrom: new Date('2024-07-15'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Available for immediate assignment',
    rate: 1800.00,
    createdBy: 3,
    updatedBy: 3,
  },
  {
    id: 6,
    employeeCode: 'FJP006',
    fullName: 'Vo Thi Fy',
    departmentId: 4,
    position: 'Business Analyst',
    email: 'vt.fy@company.com',
    skillSet: 'Requirements Analysis, Process Modeling, SQL, Power BI',
    idleFrom: new Date('2024-08-10'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Experienced analyst looking for new project',
    rate: 2300.00,
    createdBy: 2,
    updatedBy: 2,
  },
  {
    id: 7,
    employeeCode: 'FJP007',
    fullName: 'Nguyen Van Giang',
    departmentId: 1,
    position: 'Backend Developer',
    email: 'nv.giang@company.com',
    skillSet: 'Java, Spring Boot, MySQL, Redis, Microservices',
    idleFrom: new Date('2024-04-10'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'URGENT - Idle for over 3 months, need immediate action',
    rate: 2600.00,
    createdBy: 2,
    updatedBy: 4,
  },
  {
    id: 8,
    employeeCode: 'FJP008',
    fullName: 'Tran Van Huy',
    departmentId: 3,
    position: 'Manual Tester',
    email: 'tv.huy@company.com',
    skillSet: 'Manual Testing, Test Case Design, Bug Tracking, UAT',
    idleFrom: new Date('2024-07-25'),
    idleTo: undefined,
    status: ResourceStatus.ASSIGNED,
    processNote: 'Recently assigned to new project',
    rate: 1500.00,
    createdBy: 2,
    updatedBy: 5,
  },
  {
    id: 9,
    employeeCode: 'FJP009',
    fullName: 'Le Thi Yen',
    departmentId: 5,
    position: 'Project Manager',
    email: 'lt.yen@company.com',
    skillSet: 'Project Management, Agile, Scrum, Risk Management',
    idleFrom: new Date('2024-06-01'),
    idleTo: undefined,
    status: ResourceStatus.PROCESSING,
    processNote: 'Evaluating multiple project opportunities',
    rate: 3000.00,
    createdBy: 2,
    updatedBy: 2,
  },
  {
    id: 10,
    employeeCode: 'FJP010',
    fullName: 'Pham Van Khanh',
    departmentId: 1,
    position: 'Mobile Developer',
    email: 'pv.khanh@company.com',
    skillSet: 'React Native, Flutter, iOS, Android, Firebase',
    idleFrom: new Date('2024-07-20'),
    idleTo: undefined,
    status: ResourceStatus.IDLE,
    processNote: 'Mobile expert available for new projects',
    rate: 2400.00,
    createdBy: 3,
    updatedBy: 3,
  },
];
